from .main_views import *
from .admin_views import *
from .login_views import *
from .selfstudyuserprofile import *
from .selfstudyuserlab import *
from .selfstudycourse import *
from .selfstudylivecourse import *
from .selfstudyexam import *
from .selfstudycertificate import *
from .selfstudynotification import *
from .selfstudypayment import *
from .selfstudysubscriptions import *
from .selfstudydomains import *